shared:
  links:
    about: '/static_pages/aboutus'
    cite: '/static_pages/citeus'
    facebook: 'https://www.facebook.com/LifeWatch-ERIC-245225669516847'
    github: 'https://github.com/lifewatch-eric'
    help: 'https://github.com/lifewatch-eric/documentation/wiki'
    linkedin: 'https://www.linkedin.com/company/lifewatch-eric/'
    mission: 'https://www.bioontology.org/about-us/#mission'
    privacy_policy: 'https://www.lifewatch.eu/privacy-policy-2021'
    rest_api: 'http://data.bioontology.org/documentation'
    team: '/static_pages/team'
    terms: 'https://www.lifewatch.eu/terms-and-conditions'
    twitter: 'https://twitter.com/lifewatcheric'
    virtual_appliance: 'https://ontoportal.github.io/administration/'
    widgets: 'http://www.bioontology.org/wiki/NCBO_Widgets'
    wiki: 'https://github.com/lifewatch-eric/documentation/wiki'
    youtube: 'https://www.youtube.com/channel/UCP6ag3SoJ6oeisE7ibg4-pg'

development:
  links:
    release_notes: 'https://github.com/lifewatch-eric/bioportal_web_ui/releases'

staging:
  links:
    release_notes: 'https://github.com/lifewatch-eric/bioportal_web_ui/releases'

production:
  links:
    release_notes: 'https://github.com/lifewatch-eric/bioportal_web_ui/releases'

appliance:
  links:
    release_notes: 'https://www.bioontology.org/wiki/BioPortal_Virtual_Appliance_Release_Notes'
